site_name: Chopdas
copyright: Copyright &copy; 2022 - 2022 Chopdas Doc Site
theme:
  name: material
  custom_dir: overrides
  #logo: assets/mission-logo.png
  #favicon: assets/mission-logo.png
  
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.indexes # do not enable feature toc.integrate
    - navigation.top
    - navigation.sections
    - navigation.tracking
    - navigation.instant
    - search.highlight
    - search.suggest
    - search.share
    - toc.follow
    - header.autohide
  palette:
    - scheme: default
      toggle: 
        #icon: material/toggle-switch-off-outline
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      toggle:
        #icon: material/toggle-switch
        icon: material/brightness-7
        name: Switch to light mode
plugins:
  - search
  - tags
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - meta  
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - footnotes
  
extra:
  generator: false
  version:
    default: latest
    provider: mike
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js

nav:
  - Home: 
    - index.md
    #- Getting Started: getting-started.md
    #- Navigation Features: navigation-features.md
  - Developer:
    - Bits algorithm: developer/bits-algos.md
    - Regular expressions: developer/regr-exp.md
    - Build:
      - Git: developer/git.md
      - Gradle: developer/gradle.md
      - Maven: developer/maven.md
    - Security:
      - OpenSSL: developer/openssl.md
      - SSH: developer/ssh.md
  - Jainism:
    - Stotra:
      - Aarti: jainism/aarti.md
      - Logassa: jainism/logassa-stotra.md
      - Uvasa: jainism/uvasa-stotra.md
    - Samitis and Guptis: jainism/samitis-guptis.md
    - Panch Maha Vratas: jainism/panch-maha-vratas.md
  - Tags:
        - Tags index: "tags.md"